/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-02-18 22:11:37 UTC)
 * on 2016-02-26 at 23:05:08 UTC 
 * Modify at your own risk.
 */

package com.appspot.iordanis_mobilezeit.wahlzeitApi;

/**
 * Service definition for WahlzeitApi (v1).
 *
 * <p>
 * A multiclient API for Whalzeit
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link WahlzeitApiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class WahlzeitApi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the wahlzeitApi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://iordanis-mobilezeit.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "wahlzeitApi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public WahlzeitApi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  WahlzeitApi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Clients collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code WahlzeitApi wahlzeitApi = new WahlzeitApi(...);}
   *   {@code WahlzeitApi.Clients.List request = wahlzeitApi.clients().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Clients clients() {
    return new Clients();
  }

  /**
   * The "clients" collection of methods.
   */
  public class Clients {

    /**
     * Create a request for the method "clients.guests".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Guests#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Guests guests() throws java.io.IOException {
      Guests result = new Guests();
      initialize(result);
      return result;
    }

    public class Guests extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Guest> {

      private static final String REST_PATH = "clients/guests";

      /**
       * Create a request for the method "clients.guests".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Guests#execute()} method to invoke the remote operation.
       * <p> {@link
       * Guests#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Guests() {
        super(WahlzeitApi.this, "POST", REST_PATH, null, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Guest.class);
      }

      @Override
      public Guests setAlt(java.lang.String alt) {
        return (Guests) super.setAlt(alt);
      }

      @Override
      public Guests setFields(java.lang.String fields) {
        return (Guests) super.setFields(fields);
      }

      @Override
      public Guests setKey(java.lang.String key) {
        return (Guests) super.setKey(key);
      }

      @Override
      public Guests setOauthToken(java.lang.String oauthToken) {
        return (Guests) super.setOauthToken(oauthToken);
      }

      @Override
      public Guests setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Guests) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Guests setQuotaUser(java.lang.String quotaUser) {
        return (Guests) super.setQuotaUser(quotaUser);
      }

      @Override
      public Guests setUserIp(java.lang.String userIp) {
        return (Guests) super.setUserIp(userIp);
      }

      @Override
      public Guests set(String parameterName, Object value) {
        return (Guests) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "clients.users".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Users#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.User}
     * @return the request
     */
    public Users users(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.User content) throws java.io.IOException {
      Users result = new Users(content);
      initialize(result);
      return result;
    }

    public class Users extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.User> {

      private static final String REST_PATH = "clients/users";

      /**
       * Create a request for the method "clients.users".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Users#execute()} method to invoke the remote operation.
       * <p> {@link
       * Users#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.User}
       * @since 1.13
       */
      protected Users(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.User content) {
        super(WahlzeitApi.this, "POST", REST_PATH, content, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.User.class);
      }

      @Override
      public Users setAlt(java.lang.String alt) {
        return (Users) super.setAlt(alt);
      }

      @Override
      public Users setFields(java.lang.String fields) {
        return (Users) super.setFields(fields);
      }

      @Override
      public Users setKey(java.lang.String key) {
        return (Users) super.setKey(key);
      }

      @Override
      public Users setOauthToken(java.lang.String oauthToken) {
        return (Users) super.setOauthToken(oauthToken);
      }

      @Override
      public Users setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Users) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Users setQuotaUser(java.lang.String quotaUser) {
        return (Users) super.setQuotaUser(quotaUser);
      }

      @Override
      public Users setUserIp(java.lang.String userIp) {
        return (Users) super.setUserIp(userIp);
      }

      @Override
      public Users set(String parameterName, Object value) {
        return (Users) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Photos collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code WahlzeitApi wahlzeitApi = new WahlzeitApi(...);}
   *   {@code WahlzeitApi.Photos.List request = wahlzeitApi.photos().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Photos photos() {
    return new Photos();
  }

  /**
   * The "photos" collection of methods.
   */
  public class Photos {

    /**
     * Create a request for the method "photos.delete".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Delete#execute()} method to invoke the remote operation.
     *
     * @param photoId
     * @return the request
     */
    public Delete delete(java.lang.String photoId) throws java.io.IOException {
      Delete result = new Delete(photoId);
      initialize(result);
      return result;
    }

    public class Delete extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo> {

      private static final String REST_PATH = "photos/{photoId}";

      /**
       * Create a request for the method "photos.delete".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Delete#execute()} method to invoke the remote operation.
       * <p> {@link
       * Delete#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param photoId
       * @since 1.13
       */
      protected Delete(java.lang.String photoId) {
        super(WahlzeitApi.this, "DELETE", REST_PATH, null, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo.class);
        this.photoId = com.google.api.client.util.Preconditions.checkNotNull(photoId, "Required parameter photoId must be specified.");
      }

      @Override
      public Delete setAlt(java.lang.String alt) {
        return (Delete) super.setAlt(alt);
      }

      @Override
      public Delete setFields(java.lang.String fields) {
        return (Delete) super.setFields(fields);
      }

      @Override
      public Delete setKey(java.lang.String key) {
        return (Delete) super.setKey(key);
      }

      @Override
      public Delete setOauthToken(java.lang.String oauthToken) {
        return (Delete) super.setOauthToken(oauthToken);
      }

      @Override
      public Delete setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Delete) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Delete setQuotaUser(java.lang.String quotaUser) {
        return (Delete) super.setQuotaUser(quotaUser);
      }

      @Override
      public Delete setUserIp(java.lang.String userIp) {
        return (Delete) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String photoId;

      /**

       */
      public java.lang.String getPhotoId() {
        return photoId;
      }

      public Delete setPhotoId(java.lang.String photoId) {
        this.photoId = photoId;
        return this;
      }

      @Override
      public Delete set(String parameterName, Object value) {
        return (Delete) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "photos.list".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link List#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public List list() throws java.io.IOException {
      List result = new List();
      initialize(result);
      return result;
    }

    public class List extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCollection> {

      private static final String REST_PATH = "photos";

      /**
       * Create a request for the method "photos.list".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
       * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected List() {
        super(WahlzeitApi.this, "GET", REST_PATH, null, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public List setAlt(java.lang.String alt) {
        return (List) super.setAlt(alt);
      }

      @Override
      public List setFields(java.lang.String fields) {
        return (List) super.setFields(fields);
      }

      @Override
      public List setKey(java.lang.String key) {
        return (List) super.setKey(key);
      }

      @Override
      public List setOauthToken(java.lang.String oauthToken) {
        return (List) super.setOauthToken(oauthToken);
      }

      @Override
      public List setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (List) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public List setQuotaUser(java.lang.String quotaUser) {
        return (List) super.setQuotaUser(quotaUser);
      }

      @Override
      public List setUserIp(java.lang.String userIp) {
        return (List) super.setUserIp(userIp);
      }

      @Override
      public List set(String parameterName, Object value) {
        return (List) super.set(parameterName, value);
      }
    }

  }

  /**
   * Create a request for the method "getAbout".
   *
   * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
   * parameters, call the {@link GetAbout#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetAbout getAbout() throws java.io.IOException {
    GetAbout result = new GetAbout();
    initialize(result);
    return result;
  }

  public class GetAbout extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.About> {

    private static final String REST_PATH = "about";

    /**
     * Create a request for the method "getAbout".
     *
     * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
     * optional parameters, call the {@link GetAbout#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetAbout#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetAbout() {
      super(WahlzeitApi.this, "GET", REST_PATH, null, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.About.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAbout setAlt(java.lang.String alt) {
      return (GetAbout) super.setAlt(alt);
    }

    @Override
    public GetAbout setFields(java.lang.String fields) {
      return (GetAbout) super.setFields(fields);
    }

    @Override
    public GetAbout setKey(java.lang.String key) {
      return (GetAbout) super.setKey(key);
    }

    @Override
    public GetAbout setOauthToken(java.lang.String oauthToken) {
      return (GetAbout) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAbout setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAbout) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAbout setQuotaUser(java.lang.String quotaUser) {
      return (GetAbout) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAbout setUserIp(java.lang.String userIp) {
      return (GetAbout) super.setUserIp(userIp);
    }

    @Override
    public GetAbout set(String parameterName, Object value) {
      return (GetAbout) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "images".
   *
   * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
   * parameters, call the {@link Images#execute()} method to invoke the remote operation.
   *
   * @param photoId
   * @return the request
   */
  public Images images(java.lang.String photoId) throws java.io.IOException {
    Images result = new Images(photoId);
    initialize(result);
    return result;
  }

  public class Images extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.ImageCollection> {

    private static final String REST_PATH = "photos/{photoId}/images";

    /**
     * Create a request for the method "images".
     *
     * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
     * optional parameters, call the {@link Images#execute()} method to invoke the remote operation.
     * <p> {@link
     * Images#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param photoId
     * @since 1.13
     */
    protected Images(java.lang.String photoId) {
      super(WahlzeitApi.this, "GET", REST_PATH, null, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.ImageCollection.class);
      this.photoId = com.google.api.client.util.Preconditions.checkNotNull(photoId, "Required parameter photoId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Images setAlt(java.lang.String alt) {
      return (Images) super.setAlt(alt);
    }

    @Override
    public Images setFields(java.lang.String fields) {
      return (Images) super.setFields(fields);
    }

    @Override
    public Images setKey(java.lang.String key) {
      return (Images) super.setKey(key);
    }

    @Override
    public Images setOauthToken(java.lang.String oauthToken) {
      return (Images) super.setOauthToken(oauthToken);
    }

    @Override
    public Images setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Images) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Images setQuotaUser(java.lang.String quotaUser) {
      return (Images) super.setQuotaUser(quotaUser);
    }

    @Override
    public Images setUserIp(java.lang.String userIp) {
      return (Images) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String photoId;

    /**

     */
    public java.lang.String getPhotoId() {
      return photoId;
    }

    public Images setPhotoId(java.lang.String photoId) {
      this.photoId = photoId;
      return this;
    }

    @Override
    public Images set(String parameterName, Object value) {
      return (Images) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link WahlzeitApi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link WahlzeitApi}. */
    @Override
    public WahlzeitApi build() {
      return new WahlzeitApi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link WahlzeitApiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setWahlzeitApiRequestInitializer(
        WahlzeitApiRequestInitializer wahlzeitapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(wahlzeitapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
