/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-02-18 22:11:37 UTC)
 * on 2016-02-24 at 12:12:15 UTC 
 * Modify at your own risk.
 */

package com.appspot.iordanis_mobilezeit.wahlzeitApi.model;

/**
 * Model definition for ModelConfig.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the wahlzeitApi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ModelConfig extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private EmailAddress administratorEmailAddress;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String administratorMenu;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String anonUserName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private EmailAddress auditEmailAddress;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String communityMenu;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String confirmAccountFailed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String confirmAccountSucceeded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String confirmationEmailWasSent;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String continueWithShowPhoto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String continueWithShowUserHome;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String continueWithTellFriends;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String didntCheckTerms;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String emailAddressIsInvalid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String emailAddressIsMissing;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String emailWasSent;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fieldIsMissing;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String generalEmailFooter;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String generalEmailRegards;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String guestMenu;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String illegalAccessError;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String illegalArgumentError;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String information;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String inputIsInvalid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String inputIsTooLong;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String internalProcessingError;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String keepGoing;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String language;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String languageCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String loginIsIncorrect;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logoutSucceeded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private EmailAddress moderatorEmailAddress;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String moderatorMenu;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String moderatorWasInformed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String needToLoginFirst;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String needToSignupFirst;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String newLanguageSet;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String noCharacterName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String noFlaggedPhotoCases;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String noPhotoUploaded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String noSeriesName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String noTags;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String noteMaximumPhotoSize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String notifyAboutPraiseEmailBody;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String notifyAboutPraiseEmailPostScriptum;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String notifyAboutPraiseEmailSubject;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String optionsWereSet;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pageHeading;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pageMission;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pageTitle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String passwordChangeSucceeded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String passwordWasEmailed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String passwordsDontMatch;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String photoIsUnknown;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String photoUpdateSucceeded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String photoUploadFailed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String photoUploadSucceeded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileUpdateSucceeded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String resetSession;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sendEmailBodyPostfix;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sendEmailBodyPrefix;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sendEmailSubjectPrefix;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sendPasswordEmailSubject;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sendUserNameEmailSubject;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tellFriendEmailPhoto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tellFriendEmailSubject;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tellFriendEmailWebsite;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String thankYou;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String unknownEmailAddress;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String urlIsInvalid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userAlreadyExists;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userIsDisabled;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userMenu;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userNameIsReserved;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userNameIsUnknown;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userNameWasEmailed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String welcomeEmailBody;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String welcomeEmailSubject;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String welcomeEmailUserName;

  /**
   * @return value or {@code null} for none
   */
  public EmailAddress getAdministratorEmailAddress() {
    return administratorEmailAddress;
  }

  /**
   * @param administratorEmailAddress administratorEmailAddress or {@code null} for none
   */
  public ModelConfig setAdministratorEmailAddress(EmailAddress administratorEmailAddress) {
    this.administratorEmailAddress = administratorEmailAddress;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAdministratorMenu() {
    return administratorMenu;
  }

  /**
   * @param administratorMenu administratorMenu or {@code null} for none
   */
  public ModelConfig setAdministratorMenu(java.lang.String administratorMenu) {
    this.administratorMenu = administratorMenu;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAnonUserName() {
    return anonUserName;
  }

  /**
   * @param anonUserName anonUserName or {@code null} for none
   */
  public ModelConfig setAnonUserName(java.lang.String anonUserName) {
    this.anonUserName = anonUserName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public EmailAddress getAuditEmailAddress() {
    return auditEmailAddress;
  }

  /**
   * @param auditEmailAddress auditEmailAddress or {@code null} for none
   */
  public ModelConfig setAuditEmailAddress(EmailAddress auditEmailAddress) {
    this.auditEmailAddress = auditEmailAddress;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCommunityMenu() {
    return communityMenu;
  }

  /**
   * @param communityMenu communityMenu or {@code null} for none
   */
  public ModelConfig setCommunityMenu(java.lang.String communityMenu) {
    this.communityMenu = communityMenu;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getConfirmAccountFailed() {
    return confirmAccountFailed;
  }

  /**
   * @param confirmAccountFailed confirmAccountFailed or {@code null} for none
   */
  public ModelConfig setConfirmAccountFailed(java.lang.String confirmAccountFailed) {
    this.confirmAccountFailed = confirmAccountFailed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getConfirmAccountSucceeded() {
    return confirmAccountSucceeded;
  }

  /**
   * @param confirmAccountSucceeded confirmAccountSucceeded or {@code null} for none
   */
  public ModelConfig setConfirmAccountSucceeded(java.lang.String confirmAccountSucceeded) {
    this.confirmAccountSucceeded = confirmAccountSucceeded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getConfirmationEmailWasSent() {
    return confirmationEmailWasSent;
  }

  /**
   * @param confirmationEmailWasSent confirmationEmailWasSent or {@code null} for none
   */
  public ModelConfig setConfirmationEmailWasSent(java.lang.String confirmationEmailWasSent) {
    this.confirmationEmailWasSent = confirmationEmailWasSent;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContinueWithShowPhoto() {
    return continueWithShowPhoto;
  }

  /**
   * @param continueWithShowPhoto continueWithShowPhoto or {@code null} for none
   */
  public ModelConfig setContinueWithShowPhoto(java.lang.String continueWithShowPhoto) {
    this.continueWithShowPhoto = continueWithShowPhoto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContinueWithShowUserHome() {
    return continueWithShowUserHome;
  }

  /**
   * @param continueWithShowUserHome continueWithShowUserHome or {@code null} for none
   */
  public ModelConfig setContinueWithShowUserHome(java.lang.String continueWithShowUserHome) {
    this.continueWithShowUserHome = continueWithShowUserHome;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContinueWithTellFriends() {
    return continueWithTellFriends;
  }

  /**
   * @param continueWithTellFriends continueWithTellFriends or {@code null} for none
   */
  public ModelConfig setContinueWithTellFriends(java.lang.String continueWithTellFriends) {
    this.continueWithTellFriends = continueWithTellFriends;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDidntCheckTerms() {
    return didntCheckTerms;
  }

  /**
   * @param didntCheckTerms didntCheckTerms or {@code null} for none
   */
  public ModelConfig setDidntCheckTerms(java.lang.String didntCheckTerms) {
    this.didntCheckTerms = didntCheckTerms;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmailAddressIsInvalid() {
    return emailAddressIsInvalid;
  }

  /**
   * @param emailAddressIsInvalid emailAddressIsInvalid or {@code null} for none
   */
  public ModelConfig setEmailAddressIsInvalid(java.lang.String emailAddressIsInvalid) {
    this.emailAddressIsInvalid = emailAddressIsInvalid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmailAddressIsMissing() {
    return emailAddressIsMissing;
  }

  /**
   * @param emailAddressIsMissing emailAddressIsMissing or {@code null} for none
   */
  public ModelConfig setEmailAddressIsMissing(java.lang.String emailAddressIsMissing) {
    this.emailAddressIsMissing = emailAddressIsMissing;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmailWasSent() {
    return emailWasSent;
  }

  /**
   * @param emailWasSent emailWasSent or {@code null} for none
   */
  public ModelConfig setEmailWasSent(java.lang.String emailWasSent) {
    this.emailWasSent = emailWasSent;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFieldIsMissing() {
    return fieldIsMissing;
  }

  /**
   * @param fieldIsMissing fieldIsMissing or {@code null} for none
   */
  public ModelConfig setFieldIsMissing(java.lang.String fieldIsMissing) {
    this.fieldIsMissing = fieldIsMissing;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGeneralEmailFooter() {
    return generalEmailFooter;
  }

  /**
   * @param generalEmailFooter generalEmailFooter or {@code null} for none
   */
  public ModelConfig setGeneralEmailFooter(java.lang.String generalEmailFooter) {
    this.generalEmailFooter = generalEmailFooter;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGeneralEmailRegards() {
    return generalEmailRegards;
  }

  /**
   * @param generalEmailRegards generalEmailRegards or {@code null} for none
   */
  public ModelConfig setGeneralEmailRegards(java.lang.String generalEmailRegards) {
    this.generalEmailRegards = generalEmailRegards;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGuestMenu() {
    return guestMenu;
  }

  /**
   * @param guestMenu guestMenu or {@code null} for none
   */
  public ModelConfig setGuestMenu(java.lang.String guestMenu) {
    this.guestMenu = guestMenu;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIllegalAccessError() {
    return illegalAccessError;
  }

  /**
   * @param illegalAccessError illegalAccessError or {@code null} for none
   */
  public ModelConfig setIllegalAccessError(java.lang.String illegalAccessError) {
    this.illegalAccessError = illegalAccessError;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIllegalArgumentError() {
    return illegalArgumentError;
  }

  /**
   * @param illegalArgumentError illegalArgumentError or {@code null} for none
   */
  public ModelConfig setIllegalArgumentError(java.lang.String illegalArgumentError) {
    this.illegalArgumentError = illegalArgumentError;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInformation() {
    return information;
  }

  /**
   * @param information information or {@code null} for none
   */
  public ModelConfig setInformation(java.lang.String information) {
    this.information = information;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInputIsInvalid() {
    return inputIsInvalid;
  }

  /**
   * @param inputIsInvalid inputIsInvalid or {@code null} for none
   */
  public ModelConfig setInputIsInvalid(java.lang.String inputIsInvalid) {
    this.inputIsInvalid = inputIsInvalid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInputIsTooLong() {
    return inputIsTooLong;
  }

  /**
   * @param inputIsTooLong inputIsTooLong or {@code null} for none
   */
  public ModelConfig setInputIsTooLong(java.lang.String inputIsTooLong) {
    this.inputIsTooLong = inputIsTooLong;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInternalProcessingError() {
    return internalProcessingError;
  }

  /**
   * @param internalProcessingError internalProcessingError or {@code null} for none
   */
  public ModelConfig setInternalProcessingError(java.lang.String internalProcessingError) {
    this.internalProcessingError = internalProcessingError;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKeepGoing() {
    return keepGoing;
  }

  /**
   * @param keepGoing keepGoing or {@code null} for none
   */
  public ModelConfig setKeepGoing(java.lang.String keepGoing) {
    this.keepGoing = keepGoing;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLanguage() {
    return language;
  }

  /**
   * @param language language or {@code null} for none
   */
  public ModelConfig setLanguage(java.lang.String language) {
    this.language = language;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLanguageCode() {
    return languageCode;
  }

  /**
   * @param languageCode languageCode or {@code null} for none
   */
  public ModelConfig setLanguageCode(java.lang.String languageCode) {
    this.languageCode = languageCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLoginIsIncorrect() {
    return loginIsIncorrect;
  }

  /**
   * @param loginIsIncorrect loginIsIncorrect or {@code null} for none
   */
  public ModelConfig setLoginIsIncorrect(java.lang.String loginIsIncorrect) {
    this.loginIsIncorrect = loginIsIncorrect;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLogoutSucceeded() {
    return logoutSucceeded;
  }

  /**
   * @param logoutSucceeded logoutSucceeded or {@code null} for none
   */
  public ModelConfig setLogoutSucceeded(java.lang.String logoutSucceeded) {
    this.logoutSucceeded = logoutSucceeded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public EmailAddress getModeratorEmailAddress() {
    return moderatorEmailAddress;
  }

  /**
   * @param moderatorEmailAddress moderatorEmailAddress or {@code null} for none
   */
  public ModelConfig setModeratorEmailAddress(EmailAddress moderatorEmailAddress) {
    this.moderatorEmailAddress = moderatorEmailAddress;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getModeratorMenu() {
    return moderatorMenu;
  }

  /**
   * @param moderatorMenu moderatorMenu or {@code null} for none
   */
  public ModelConfig setModeratorMenu(java.lang.String moderatorMenu) {
    this.moderatorMenu = moderatorMenu;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getModeratorWasInformed() {
    return moderatorWasInformed;
  }

  /**
   * @param moderatorWasInformed moderatorWasInformed or {@code null} for none
   */
  public ModelConfig setModeratorWasInformed(java.lang.String moderatorWasInformed) {
    this.moderatorWasInformed = moderatorWasInformed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNeedToLoginFirst() {
    return needToLoginFirst;
  }

  /**
   * @param needToLoginFirst needToLoginFirst or {@code null} for none
   */
  public ModelConfig setNeedToLoginFirst(java.lang.String needToLoginFirst) {
    this.needToLoginFirst = needToLoginFirst;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNeedToSignupFirst() {
    return needToSignupFirst;
  }

  /**
   * @param needToSignupFirst needToSignupFirst or {@code null} for none
   */
  public ModelConfig setNeedToSignupFirst(java.lang.String needToSignupFirst) {
    this.needToSignupFirst = needToSignupFirst;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNewLanguageSet() {
    return newLanguageSet;
  }

  /**
   * @param newLanguageSet newLanguageSet or {@code null} for none
   */
  public ModelConfig setNewLanguageSet(java.lang.String newLanguageSet) {
    this.newLanguageSet = newLanguageSet;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNoCharacterName() {
    return noCharacterName;
  }

  /**
   * @param noCharacterName noCharacterName or {@code null} for none
   */
  public ModelConfig setNoCharacterName(java.lang.String noCharacterName) {
    this.noCharacterName = noCharacterName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNoFlaggedPhotoCases() {
    return noFlaggedPhotoCases;
  }

  /**
   * @param noFlaggedPhotoCases noFlaggedPhotoCases or {@code null} for none
   */
  public ModelConfig setNoFlaggedPhotoCases(java.lang.String noFlaggedPhotoCases) {
    this.noFlaggedPhotoCases = noFlaggedPhotoCases;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNoPhotoUploaded() {
    return noPhotoUploaded;
  }

  /**
   * @param noPhotoUploaded noPhotoUploaded or {@code null} for none
   */
  public ModelConfig setNoPhotoUploaded(java.lang.String noPhotoUploaded) {
    this.noPhotoUploaded = noPhotoUploaded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNoSeriesName() {
    return noSeriesName;
  }

  /**
   * @param noSeriesName noSeriesName or {@code null} for none
   */
  public ModelConfig setNoSeriesName(java.lang.String noSeriesName) {
    this.noSeriesName = noSeriesName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNoTags() {
    return noTags;
  }

  /**
   * @param noTags noTags or {@code null} for none
   */
  public ModelConfig setNoTags(java.lang.String noTags) {
    this.noTags = noTags;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNoteMaximumPhotoSize() {
    return noteMaximumPhotoSize;
  }

  /**
   * @param noteMaximumPhotoSize noteMaximumPhotoSize or {@code null} for none
   */
  public ModelConfig setNoteMaximumPhotoSize(java.lang.String noteMaximumPhotoSize) {
    this.noteMaximumPhotoSize = noteMaximumPhotoSize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNotifyAboutPraiseEmailBody() {
    return notifyAboutPraiseEmailBody;
  }

  /**
   * @param notifyAboutPraiseEmailBody notifyAboutPraiseEmailBody or {@code null} for none
   */
  public ModelConfig setNotifyAboutPraiseEmailBody(java.lang.String notifyAboutPraiseEmailBody) {
    this.notifyAboutPraiseEmailBody = notifyAboutPraiseEmailBody;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNotifyAboutPraiseEmailPostScriptum() {
    return notifyAboutPraiseEmailPostScriptum;
  }

  /**
   * @param notifyAboutPraiseEmailPostScriptum notifyAboutPraiseEmailPostScriptum or {@code null} for none
   */
  public ModelConfig setNotifyAboutPraiseEmailPostScriptum(java.lang.String notifyAboutPraiseEmailPostScriptum) {
    this.notifyAboutPraiseEmailPostScriptum = notifyAboutPraiseEmailPostScriptum;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNotifyAboutPraiseEmailSubject() {
    return notifyAboutPraiseEmailSubject;
  }

  /**
   * @param notifyAboutPraiseEmailSubject notifyAboutPraiseEmailSubject or {@code null} for none
   */
  public ModelConfig setNotifyAboutPraiseEmailSubject(java.lang.String notifyAboutPraiseEmailSubject) {
    this.notifyAboutPraiseEmailSubject = notifyAboutPraiseEmailSubject;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOptionsWereSet() {
    return optionsWereSet;
  }

  /**
   * @param optionsWereSet optionsWereSet or {@code null} for none
   */
  public ModelConfig setOptionsWereSet(java.lang.String optionsWereSet) {
    this.optionsWereSet = optionsWereSet;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPageHeading() {
    return pageHeading;
  }

  /**
   * @param pageHeading pageHeading or {@code null} for none
   */
  public ModelConfig setPageHeading(java.lang.String pageHeading) {
    this.pageHeading = pageHeading;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPageMission() {
    return pageMission;
  }

  /**
   * @param pageMission pageMission or {@code null} for none
   */
  public ModelConfig setPageMission(java.lang.String pageMission) {
    this.pageMission = pageMission;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPageTitle() {
    return pageTitle;
  }

  /**
   * @param pageTitle pageTitle or {@code null} for none
   */
  public ModelConfig setPageTitle(java.lang.String pageTitle) {
    this.pageTitle = pageTitle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPasswordChangeSucceeded() {
    return passwordChangeSucceeded;
  }

  /**
   * @param passwordChangeSucceeded passwordChangeSucceeded or {@code null} for none
   */
  public ModelConfig setPasswordChangeSucceeded(java.lang.String passwordChangeSucceeded) {
    this.passwordChangeSucceeded = passwordChangeSucceeded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPasswordWasEmailed() {
    return passwordWasEmailed;
  }

  /**
   * @param passwordWasEmailed passwordWasEmailed or {@code null} for none
   */
  public ModelConfig setPasswordWasEmailed(java.lang.String passwordWasEmailed) {
    this.passwordWasEmailed = passwordWasEmailed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPasswordsDontMatch() {
    return passwordsDontMatch;
  }

  /**
   * @param passwordsDontMatch passwordsDontMatch or {@code null} for none
   */
  public ModelConfig setPasswordsDontMatch(java.lang.String passwordsDontMatch) {
    this.passwordsDontMatch = passwordsDontMatch;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPhotoIsUnknown() {
    return photoIsUnknown;
  }

  /**
   * @param photoIsUnknown photoIsUnknown or {@code null} for none
   */
  public ModelConfig setPhotoIsUnknown(java.lang.String photoIsUnknown) {
    this.photoIsUnknown = photoIsUnknown;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPhotoUpdateSucceeded() {
    return photoUpdateSucceeded;
  }

  /**
   * @param photoUpdateSucceeded photoUpdateSucceeded or {@code null} for none
   */
  public ModelConfig setPhotoUpdateSucceeded(java.lang.String photoUpdateSucceeded) {
    this.photoUpdateSucceeded = photoUpdateSucceeded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPhotoUploadFailed() {
    return photoUploadFailed;
  }

  /**
   * @param photoUploadFailed photoUploadFailed or {@code null} for none
   */
  public ModelConfig setPhotoUploadFailed(java.lang.String photoUploadFailed) {
    this.photoUploadFailed = photoUploadFailed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPhotoUploadSucceeded() {
    return photoUploadSucceeded;
  }

  /**
   * @param photoUploadSucceeded photoUploadSucceeded or {@code null} for none
   */
  public ModelConfig setPhotoUploadSucceeded(java.lang.String photoUploadSucceeded) {
    this.photoUploadSucceeded = photoUploadSucceeded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileUpdateSucceeded() {
    return profileUpdateSucceeded;
  }

  /**
   * @param profileUpdateSucceeded profileUpdateSucceeded or {@code null} for none
   */
  public ModelConfig setProfileUpdateSucceeded(java.lang.String profileUpdateSucceeded) {
    this.profileUpdateSucceeded = profileUpdateSucceeded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getResetSession() {
    return resetSession;
  }

  /**
   * @param resetSession resetSession or {@code null} for none
   */
  public ModelConfig setResetSession(java.lang.String resetSession) {
    this.resetSession = resetSession;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSendEmailBodyPostfix() {
    return sendEmailBodyPostfix;
  }

  /**
   * @param sendEmailBodyPostfix sendEmailBodyPostfix or {@code null} for none
   */
  public ModelConfig setSendEmailBodyPostfix(java.lang.String sendEmailBodyPostfix) {
    this.sendEmailBodyPostfix = sendEmailBodyPostfix;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSendEmailBodyPrefix() {
    return sendEmailBodyPrefix;
  }

  /**
   * @param sendEmailBodyPrefix sendEmailBodyPrefix or {@code null} for none
   */
  public ModelConfig setSendEmailBodyPrefix(java.lang.String sendEmailBodyPrefix) {
    this.sendEmailBodyPrefix = sendEmailBodyPrefix;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSendEmailSubjectPrefix() {
    return sendEmailSubjectPrefix;
  }

  /**
   * @param sendEmailSubjectPrefix sendEmailSubjectPrefix or {@code null} for none
   */
  public ModelConfig setSendEmailSubjectPrefix(java.lang.String sendEmailSubjectPrefix) {
    this.sendEmailSubjectPrefix = sendEmailSubjectPrefix;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSendPasswordEmailSubject() {
    return sendPasswordEmailSubject;
  }

  /**
   * @param sendPasswordEmailSubject sendPasswordEmailSubject or {@code null} for none
   */
  public ModelConfig setSendPasswordEmailSubject(java.lang.String sendPasswordEmailSubject) {
    this.sendPasswordEmailSubject = sendPasswordEmailSubject;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSendUserNameEmailSubject() {
    return sendUserNameEmailSubject;
  }

  /**
   * @param sendUserNameEmailSubject sendUserNameEmailSubject or {@code null} for none
   */
  public ModelConfig setSendUserNameEmailSubject(java.lang.String sendUserNameEmailSubject) {
    this.sendUserNameEmailSubject = sendUserNameEmailSubject;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTellFriendEmailPhoto() {
    return tellFriendEmailPhoto;
  }

  /**
   * @param tellFriendEmailPhoto tellFriendEmailPhoto or {@code null} for none
   */
  public ModelConfig setTellFriendEmailPhoto(java.lang.String tellFriendEmailPhoto) {
    this.tellFriendEmailPhoto = tellFriendEmailPhoto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTellFriendEmailSubject() {
    return tellFriendEmailSubject;
  }

  /**
   * @param tellFriendEmailSubject tellFriendEmailSubject or {@code null} for none
   */
  public ModelConfig setTellFriendEmailSubject(java.lang.String tellFriendEmailSubject) {
    this.tellFriendEmailSubject = tellFriendEmailSubject;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTellFriendEmailWebsite() {
    return tellFriendEmailWebsite;
  }

  /**
   * @param tellFriendEmailWebsite tellFriendEmailWebsite or {@code null} for none
   */
  public ModelConfig setTellFriendEmailWebsite(java.lang.String tellFriendEmailWebsite) {
    this.tellFriendEmailWebsite = tellFriendEmailWebsite;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getThankYou() {
    return thankYou;
  }

  /**
   * @param thankYou thankYou or {@code null} for none
   */
  public ModelConfig setThankYou(java.lang.String thankYou) {
    this.thankYou = thankYou;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUnknownEmailAddress() {
    return unknownEmailAddress;
  }

  /**
   * @param unknownEmailAddress unknownEmailAddress or {@code null} for none
   */
  public ModelConfig setUnknownEmailAddress(java.lang.String unknownEmailAddress) {
    this.unknownEmailAddress = unknownEmailAddress;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUrlIsInvalid() {
    return urlIsInvalid;
  }

  /**
   * @param urlIsInvalid urlIsInvalid or {@code null} for none
   */
  public ModelConfig setUrlIsInvalid(java.lang.String urlIsInvalid) {
    this.urlIsInvalid = urlIsInvalid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserAlreadyExists() {
    return userAlreadyExists;
  }

  /**
   * @param userAlreadyExists userAlreadyExists or {@code null} for none
   */
  public ModelConfig setUserAlreadyExists(java.lang.String userAlreadyExists) {
    this.userAlreadyExists = userAlreadyExists;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserIsDisabled() {
    return userIsDisabled;
  }

  /**
   * @param userIsDisabled userIsDisabled or {@code null} for none
   */
  public ModelConfig setUserIsDisabled(java.lang.String userIsDisabled) {
    this.userIsDisabled = userIsDisabled;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserMenu() {
    return userMenu;
  }

  /**
   * @param userMenu userMenu or {@code null} for none
   */
  public ModelConfig setUserMenu(java.lang.String userMenu) {
    this.userMenu = userMenu;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserNameIsReserved() {
    return userNameIsReserved;
  }

  /**
   * @param userNameIsReserved userNameIsReserved or {@code null} for none
   */
  public ModelConfig setUserNameIsReserved(java.lang.String userNameIsReserved) {
    this.userNameIsReserved = userNameIsReserved;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserNameIsUnknown() {
    return userNameIsUnknown;
  }

  /**
   * @param userNameIsUnknown userNameIsUnknown or {@code null} for none
   */
  public ModelConfig setUserNameIsUnknown(java.lang.String userNameIsUnknown) {
    this.userNameIsUnknown = userNameIsUnknown;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserNameWasEmailed() {
    return userNameWasEmailed;
  }

  /**
   * @param userNameWasEmailed userNameWasEmailed or {@code null} for none
   */
  public ModelConfig setUserNameWasEmailed(java.lang.String userNameWasEmailed) {
    this.userNameWasEmailed = userNameWasEmailed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWelcomeEmailBody() {
    return welcomeEmailBody;
  }

  /**
   * @param welcomeEmailBody welcomeEmailBody or {@code null} for none
   */
  public ModelConfig setWelcomeEmailBody(java.lang.String welcomeEmailBody) {
    this.welcomeEmailBody = welcomeEmailBody;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWelcomeEmailSubject() {
    return welcomeEmailSubject;
  }

  /**
   * @param welcomeEmailSubject welcomeEmailSubject or {@code null} for none
   */
  public ModelConfig setWelcomeEmailSubject(java.lang.String welcomeEmailSubject) {
    this.welcomeEmailSubject = welcomeEmailSubject;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWelcomeEmailUserName() {
    return welcomeEmailUserName;
  }

  /**
   * @param welcomeEmailUserName welcomeEmailUserName or {@code null} for none
   */
  public ModelConfig setWelcomeEmailUserName(java.lang.String welcomeEmailUserName) {
    this.welcomeEmailUserName = welcomeEmailUserName;
    return this;
  }

  @Override
  public ModelConfig set(String fieldName, Object value) {
    return (ModelConfig) super.set(fieldName, value);
  }

  @Override
  public ModelConfig clone() {
    return (ModelConfig) super.clone();
  }

}
